#!/usr/bin/env node
/* One-command configuration for Firebase + Telegram.
 *
 *   node scripts/configure.js \
 *     --firebase '{"apiKey":"...","authDomain":"...","projectId":"...","appId":"..."}' \
 *     --telegram-token "123456:ABC-DEF..." \
 *     --telegram-chat "-1001234567890"
 *
 * - Firebase config  → written into public/firebase-config.js (this file is
 *   PUBLIC by design — Firebase web API keys are not secrets; safety comes
 *   from Auth settings + Authorized domains).
 * - Telegram token/chat → written into .env (gitignored; the bot token IS a
 *   secret). On Render/Railway, set the same two vars in the dashboard.
 *
 * Run `node scripts/telegram-check.js` afterwards to verify.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const getArg = (name) => {
  const i = args.indexOf('--' + name);
  return i >= 0 && args[i + 1] ? args[i + 1] : null;
};

const ROOT = path.join(__dirname, '..');
const FIREBASE_FILE = path.join(ROOT, 'public', 'firebase-config.js');
const ENV_FILE = path.join(ROOT, '.env');

let did = [];

/* ------------------------- firebase ------------------------- */
const fbRaw = getArg('firebase');
if (fbRaw) {
  let cfg;
  try { cfg = JSON.parse(fbRaw); }
  catch { console.error('✗ --firebase is not valid JSON'); process.exit(1); }
  const required = ['apiKey', 'authDomain', 'projectId'];
  const missing = required.filter((k) => !cfg[k]);
  if (missing.length) { console.error('✗ firebase config missing: ' + missing.join(', ')); process.exit(1); }
  if (cfg.apiKey.startsWith('AIza') === false) {
    console.warn('⚠ apiKey does not start with "AIza" — double-check you copied the WEB app config.');
  }
  const body = `/* Ghost Chat — Firebase configuration.
 * Generated by scripts/configure.js on ${new Date().toISOString().slice(0, 10)}.
 * This file is public by design (Firebase web keys are not secrets).
 * Remember: Auth → Sign-in method → enable Email/Password (+ Google),
 * and add your hosting domains under Auth → Settings → Authorized domains.
 */
window.FIREBASE_CONFIG = ${JSON.stringify({
    apiKey: cfg.apiKey,
    authDomain: cfg.authDomain,
    projectId: cfg.projectId,
    storageBucket: cfg.storageBucket || undefined,
    messagingSenderId: cfg.messagingSenderId || undefined,
    appId: cfg.appId || undefined,
    emulator: false,
  }, null, 2)};
`;
  fs.writeFileSync(FIREBASE_FILE, body);
  did.push(`✓ Firebase config written → public/firebase-config.js (project: ${cfg.projectId}, emulator OFF)`);
}

/* ------------------------- telegram ------------------------- */
const token = getArg('telegram-token');
const chat = getArg('telegram-chat');
if (token || chat) {
  let lines = [];
  try { lines = fs.readFileSync(ENV_FILE, 'utf8').split('\n'); } catch {}
  const upsert = (key, value) => {
    const re = new RegExp(`^${key}=`);
    const i = lines.findIndex((l) => re.test(l));
    if (i >= 0) lines[i] = `${key}=${value}`; else lines.push(`${key}=${value}`);
  };
  if (token) upsert('TELEGRAM_BOT_TOKEN', token);
  if (chat) upsert('TELEGRAM_CHAT_ID', chat);
  if (!lines.some((l) => l.startsWith('#'))) {
    lines.unshift('# Ghost Chat local secrets — NEVER commit this file.', '');
  }
  fs.writeFileSync(ENV_FILE, lines.join('\n').replace(/\n{3,}/g, '\n\n'));
  did.push(`✓ Telegram vars written → .env (${[token && 'TELEGRAM_BOT_TOKEN', chat && 'TELEGRAM_CHAT_ID'].filter(Boolean).join(', ')})`);
}

if (!did.length) {
  console.log('Nothing to do. Usage:');
  console.log('  node scripts/configure.js --firebase \'<json>\' --telegram-token <token> --telegram-chat <chatId>');
  process.exit(1);
}
console.log(did.join('\n'));
console.log('\nNext: node scripts/telegram-check.js   (validates bot + shows chat ids)');
console.log('On Render/Railway: set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID as env vars in the dashboard.');
